### ISSUE TITLE
Unexpected Class for GeoIP - Laravel 4.2

### ISSUE THREAD

**Issue by imarkdesigns** [antonioribeiro/firewall#37]
After i update your codes... and when i re-run the `php artisan migrate` i have this new line or error again.

```
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'","file":"\/home\/sitename\/vendor\/pragmarx\/support\/src\/geoip\/GeoIp.php","line":38}}
```

Again, everything are in placed... it looks like, the codes was referring to Laravel 5.2? or it is flexible to 4.2?

Note: Also i tried to use the old GeoIP.php file and seems to work fine, though the problem here is, It never redirect to certain page if the IP or country was blocked... 

Routes was served like this:

```
	Route::group(array('before' => 'fw-block-bl'), function() {
		Route::get('blockd', function(){
			return View::make('_home.blockd');
		});
		
		Route::group(array('before' => 'fw-allow-wl'), function() {
			Route::get('/', 'PagesController@homeLatest');
		});	
	});
```

But if i am visiting the page, it always went to blank page... which is weird in my understanding.

**Comment by lflaszlo** [comment]
+1

**Comment by nepos87** [comment]
:+1:

**Comment by FiloSpaTeam** [comment]
:+1:

**Comment by antonioribeiro** [comment]
Closing in favor of: https://github.com/antonioribeiro/firewall/issues/36

**Comment by antonioribeiro** [comment]
Fixed.

**Comment by imarkdesigns** [comment]
Hi Antonio... After giving it a try again, here's the output of the new installation from Laravel 4.2/Bluehost VPS.

And, just wanted to clarify if i should also need to install the tracker?
And, whenever i try to block a certain country, it is not working... It ends on blank screen instead of /warning page. I did follow correctly but still no luck.

![screenshot 2015-11-30 10 01 55](https://cloud.githubusercontent.com/assets/1100419/11462082/d80d1826-9749-11e5-96bb-cc4ec4edd042.png)
